### ISSUE TITLE
Invalidating cache with update commands

### ISSUE THREAD

**Issue by filiptronicek** [Asjas/prisma-redis-middleware#29]
If the database gets updated, the associated cache keys should be invalidated (either by updating or deleting).

**Comment by Asjas** [comment]
I added `Basic Cache Invalidation` in version [1.1.0](https://github.com/Asjas/prisma-redis-middleware/releases/tag/v1.1.0).

I'm basically searching the Redis cache for all keys that matches a model when a Prisma `mutation` action happens. I then delete all those keys from Redis.

`model` in this case would be `User`, `Post` or similar.

```js
const keys = await redis.keys(`${model}:*`);
const deletedKeys = await redis.del(keys);
```

So if `create` or `updateMany` is called on the `User` model, all cached `keys` that refer to the `User` model will be deleted.

**Comment by Asjas** [comment]
I know most Prisma actions (queries and mutations) usually include an `id` field in the `args` or `next` return value.

I don't know if this is true for all `actions` or all `databases` that are supported by Prisma, but that could be something that would allow me to create a more refined cache where only cached queries that match a `model` AND that match an `id` field can be deleted.

I'm curious what other people's opinion on this would be?

**Comment by f-o-w-l** [comment]
> I know most Prisma actions (queries and mutations) usually include an `id` field in the `args` or `next` return value.
> 
> I don't know if this is true for all `actions` or all `databases` that are supported by Prisma, but that could be something that would allow me to create a more refined cache where only cached queries that match a `model` AND that match an `id` field can be deleted.
> 
> I'm curious what other people's opinion on this would be?

It makes sense for me to call it a primary key for each model. Models are basically tables, right? If so, then there should only be one primary key per model. Disclaimer, I haven't used Prisma, I'm currently learning it. Referencing #62, I think it would be great to have this kind of API:

```
prismaClient.$use(
  createPrismaRedisCache({
    models: [
      {
        model: "User",
        primaryKey: "id",
      },
      {
        model: "Post",
        cacheTime: 900,
        primaryKey: "postId",
        excludeCacheMethods: ["aggregate"],
      }
    ],
    defaultCacheTime: 300,
    redis,
    defaultExcludeCacheMethods: ["findMany"],
  }),
);
```

The docs could mention that if a `primaryKey` isn't specified, then the full model is deleted from cache after any mutation, otherwise the mutation will only delete queries that match the model and `primaryKey`. I think it makes sense to fully flush the model cache by default instead of checking for the "id" property specifically by default. I like the idea of default fallbacks not just for the `cacheTime`, I can't think of any downside to allowing `excludeCacheMethods` to be specified per model. What do you think?

**Comment by Asjas** [comment]
`v2.0.0` has been released.
